name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f410d7f0357f59ed7571f7bc25a02514a4e632224f0b660a539f82a4afa789f"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
