name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dac53570d65d86b87bb05567daf2119d1abf0e0f80ca4578320b7486fccfddf4"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
