name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f35ced74f089ca3837f2b4c6823197d3e6cb7a2eb9c7465228c8f39d547345ba"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
